{"cells":[{"cell_type":"code","execution_count":88,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":10763,"status":"ok","timestamp":1711888873654,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"K6_Z0SL9bNfQ","outputId":"4c49574c-3ae1-4262-bb36-c694a805d385"},"outputs":[{"name":"stdout","output_type":"stream","text":["Mounted at /content/drive\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","pwd: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","ls: cannot open directory '.': Transport endpoint is not connected\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive', force_remount=True)\n","\n","!pwd\n","!ls"]},{"cell_type":"code","execution_count":89,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":9,"status":"ok","timestamp":1711888881968,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"15Ofc1BnZXn-","outputId":"959d6cd9-6b4d-4f41-af52-ad548358703d"},"outputs":[{"name":"stdout","output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","pwd: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n"]}],"source":["!pwd"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"GAAxQ6PYbjo8"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-90-edb22cf196a1\u003e\", line 2, in \u003ccell line: 2\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/ADNE/ASSIGNMENT')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-90-edb22cf196a1\u003e\", line 2, in \u003ccell line: 2\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/ADNE/ASSIGNMENT')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-90-edb22cf196a1\u003e\", line 2, in \u003ccell line: 2\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/ADNE/ASSIGNMENT')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Go to the folder where we want to clone the repository\n","%cd /content/drive/MyDrive/ADNE/ASSIGNMENT"]},{"cell_type":"code","execution_count":71,"metadata":{"executionInfo":{"elapsed":421,"status":"ok","timestamp":1711886969978,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"yh3hqjXwMZtA"},"outputs":[],"source":["# Auntentify out GitHub account\n","!git config --global user.email \"202312300@alu.comillas.edu\"\n","!git config --global user.name \"miberar123\""]},{"cell_type":"code","execution_count":75,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":1957,"status":"ok","timestamp":1711887580548,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"qYMN24R5bowF","outputId":"a84b4d36-410c-4e2e-dee0-37b9c7572b33"},"outputs":[{"name":"stdout","output_type":"stream","text":["Cloning into 'SentimentAnalysis'...\n","remote: Enumerating objects: 19, done.\u001b[K\n","remote: Counting objects: 100% (19/19), done.\u001b[K\n","remote: Compressing objects: 100% (14/14), done.\u001b[K\n","remote: Total 19 (delta 3), reused 7 (delta 1), pack-reused 0\u001b[K\n","Receiving objects: 100% (19/19), 450.35 KiB | 2.30 MiB/s, done.\n","Resolving deltas: 100% (3/3), done.\n"]}],"source":["# Clone the repository\n","!git clone https://github.com/miberar123/SentimentAnalysis.git"]},{"cell_type":"code","execution_count":76,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":444,"status":"ok","timestamp":1711887583909,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"BpwGbQr8byGH","outputId":"9005ab6f-4946-42fa-8288-21bc05e7ade0"},"outputs":[{"name":"stdout","output_type":"stream","text":["/content/drive/MyDrive/ADNE/ASSIGNMENT/SentimentAnalysis\n","\u001b[0m\u001b[01;34m.git\u001b[0m/  README.md  YOLO.ipynb\n"]}],"source":["# Go to the repository folder and check what it is inside\n","%cd SentimentAnalysis\n","%ls -a"]},{"cell_type":"code","execution_count":77,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":307,"status":"ok","timestamp":1711887593287,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"5zjPQHyAb6RZ","outputId":"532f72e7-f141-4d86-cd6c-ce68b57eaa91"},"outputs":[{"name":"stdout","output_type":"stream","text":["On branch main\n","Your branch is up to date with 'origin/main'.\n","\n","nothing to commit, working tree clean\n"]}],"source":["# Check the status\n","!git status"]},{"cell_type":"code","execution_count":78,"metadata":{"executionInfo":{"elapsed":289,"status":"ok","timestamp":1711887610445,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"lY0O8U8zNQZa"},"outputs":[],"source":["# Let's move this jupyter notebook to the repository\n","!mv /content/drive/MyDrive/ADNE/ASSIGNMENT/cloning_repo.ipynb /content/drive/MyDrive/ADNE/ASSIGNMENT/SentimentAnalysis"]},{"cell_type":"code","execution_count":79,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":477,"status":"ok","timestamp":1711887613867,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"8X1zOtaNNn42","outputId":"f4a9179b-880e-4e0e-aab3-11f978ffb9e7"},"outputs":[{"name":"stdout","output_type":"stream","text":["On branch main\n","Your branch is up to date with 'origin/main'.\n","\n","Untracked files:\n","  (use \"git add \u003cfile\u003e...\" to include in what will be committed)\n","\t\u001b[31mcloning_repo.ipynb\u001b[m\n","\n","nothing added to commit but untracked files present (use \"git add\" to track)\n"]}],"source":["# Check the status\n","!git status"]},{"cell_type":"code","execution_count":80,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":1014,"status":"ok","timestamp":1711887627494,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"2yb2_pLZdDao","outputId":"5dca0273-e343-4bf9-d2e4-27b1f98368d9"},"outputs":[{"name":"stdout","output_type":"stream","text":["[main e577a59] Adding cloning_repo jupyter notebook to the repository\n"," 1 file changed, 1 insertion(+)\n"," create mode 100644 cloning_repo.ipynb\n"]}],"source":["# This file has been added the SentimentAnalysis folder, let's add and commit the change!\n","!git add .\n","!git commit -m \"Adding cloning_repo jupyter notebook to the repository\""]},{"cell_type":"code","execution_count":81,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":377,"status":"ok","timestamp":1711887633120,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"ZeVULeRiPxO4","outputId":"c3ce899d-ce60-44ce-946c-b2a2085f35a3"},"outputs":[{"name":"stdout","output_type":"stream","text":["origin\thttps://github.com/miberar123/SentimentAnalysis.git (fetch)\n","origin\thttps://github.com/miberar123/SentimentAnalysis.git (push)\n"]}],"source":["# List the urls of the remote repo\n","!git remote -v"]},{"cell_type":"markdown","metadata":{"id":"2Oojm2uJP-rf"},"source":["‘origin’ is the default remote name assigned by the ‘git clone’ command.\n","\n","This remote reference gives both ‘fetch’ and ‘push’ access to the cloned working directory."]},{"cell_type":"code","execution_count":54,"metadata":{"executionInfo":{"elapsed":352,"status":"ok","timestamp":1711884365678,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"VsGL7NwdQGsx"},"outputs":[],"source":["# We could add another remote reference 'test' to the same commit\n","!git remote add origin2 https://github.com/miberar123/test.git"]},{"cell_type":"code","execution_count":55,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":531,"status":"ok","timestamp":1711884377005,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"RtP0fO2cQnx-","outputId":"6faa32f0-3984-4f50-c156-a1a909252b58"},"outputs":[{"name":"stdout","output_type":"stream","text":["origin\thttps://github.com/miberar123/SentimentAnalysis.git (fetch)\n","origin\thttps://github.com/miberar123/SentimentAnalysis.git (push)\n","origin2\thttps://github.com/miberar123/test.git (fetch)\n","origin2\thttps://github.com/miberar123/test.git (push)\n"]}],"source":["!git remote -v"]},{"cell_type":"code","execution_count":56,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":431,"status":"ok","timestamp":1711884462556,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"41pfGgz7Qz9-","outputId":"b9612681-614e-4e3e-efef-cf375f4d60ec"},"outputs":[{"name":"stdout","output_type":"stream","text":["  \u001b[31morigin/HEAD\u001b[m -\u003e origin/main\n","  \u001b[31morigin/main\u001b[m\n"]}],"source":["# List the remote branches\n","!git branch -r"]},{"cell_type":"code","execution_count":57,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":392,"status":"ok","timestamp":1711884509943,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"tzgfpsCPRDyZ","outputId":"3ba778b4-45cc-41a3-a55b-30a9606dce87"},"outputs":[{"name":"stdout","output_type":"stream","text":["* \u001b[32mmain\u001b[m 72ed873 [\u001b[34morigin/main\u001b[m: ahead 1] Adding cloning_repo jupyter notebook to the repository\n"]}],"source":["# List the local branches tracking remote branches\n","!git branch -vv"]},{"cell_type":"code","execution_count":58,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":1119,"status":"ok","timestamp":1711884604976,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"dpZvfH0fRdPt","outputId":"8e3c90fb-bda0-43eb-f775-a4bc2adb4713"},"outputs":[{"name":"stdout","output_type":"stream","text":["* \u001b[32mmain\u001b[m\n","  \u001b[31mremotes/origin/HEAD\u001b[m -\u003e origin/main\n","  \u001b[31mremotes/origin/main\u001b[m\n"]}],"source":["# List all the branches, remote and local\n","!git branch -a"]},{"cell_type":"code","execution_count":86,"metadata":{"executionInfo":{"elapsed":290,"status":"ok","timestamp":1711888256952,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"RzNS2FbddFBq"},"outputs":[],"source":["# To save our commits in GitHub, we need to push them!\n","token = \"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\"\n","!git remote set-url origin https://x-access-token:{token}@github.com/miberar123/SentimentAnalysis\n"]},{"cell_type":"code","execution_count":87,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":349,"status":"ok","timestamp":1711888272414,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"5XRSG0kOffJl","outputId":"27cf402c-5aea-4688-ff66-f4e59fe65e63"},"outputs":[{"name":"stdout","output_type":"stream","text":["remote: Support for password authentication was removed on August 13, 2021.\n","remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.\n","fatal: Authentication failed for 'https://github.com/miberar123/SentimentAnalysis/'\n"]}],"source":["!git push"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":315,"status":"ok","timestamp":1711882951484,"user":{"displayName":"Minerva Bermejo","userId":"13935528276600543410"},"user_tz":-120},"id":"oFbIk9mAf8bx","outputId":"41ddb3ad-101e-4591-ae58-70df69056389"},"outputs":[{"name":"stdout","output_type":"stream","text":["origin\thttps://github.com/miberar123/SentimentAnalysis.git (fetch)\n","origin\thttps://github.com/miberar123/SentimentAnalysis.git (push)\n"]}],"source":["!git remote -v"]}],"metadata":{"colab":{"authorship_tag":"ABX9TyO3MGuMraQT23xlhZJWy9QQ","name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}